language: python
python:
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO 
  - pip install pep8 
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 modeldict"
  - pyflakes -x W modeldict
script:
  - python setup.py test
